name: Github Actions 실행시켜보기

on:
  push:
    branches:
      - main
  
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Printing Hello World
        run: echo "Hello World"
        